server:
  port: 8761
spring:
  application:
    name: Eureka-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
        default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost